#!/bin/sh
. /etc/rc.d/init.d/functions

DAEMON="/home/ec2-user/PocketMine-MP_alpha"
SCRIPT="./start.sh"
LOG_FILE="daemon"
LOG_FILE_EXT="log"
LOG_ARCHIVE="logs"
USER="ec2-user"
LOCK_FILE="minecraftPE.Locked"

do_start()
{
        if [ ! -f "$DAEMON/$LOCK_FILE" ] ; then
                echo -n $"Starting $SERVER: "
                runuser -l "$USER" -c "$DAEMON/$SCRIPT >> $DAEMON/$LOG_FILE.$LOG_FILE_EXT &" && echo_success || echo_failure
                RETVAL=$?
                echo
                [ $RETVAL -eq 0 ] && touch $DAEMON/$LOCK_FILE
        else
                echo "$SERVER is locked."
                RETVAL=1
        fi
}
do_stop()
{
        echo -n $"Stopping $SERVER: "
        pid=`ps auxwf|grep PocketMine|grep -v grep|awk '{print $2}'`

        kill -15 $pid > /dev/null 2>&1 && echo_success || echo_failure
        RETVAL=$?
	rm -f $DAEMON/$LOCK_FILE
        echo [ $RETVAL -eq 0 ] && rm -f $DAEMON/$LOCK_FILE
	DATE=`date +%Y%m%d-%H:%M:%S`
	mv $DAEMON/$LOG_FILE.$LOG_FILE_EXT $DAEMON/$LOG_ARCHIVE/$LOG_FILE.$DATE.$LOG_FILE_EXT
	gzip $DAEMON/$LOG_ARCHIVE/$LOG_FILE.$DATE.$LOG_FILE_EXT
}

case "$1" in
        start)
                do_start
                ;;
        stop)
                do_stop
                ;;
        restart)
                do_stop
		sleep 10
                do_start
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                RETVAL=1
esac

exit $RETVAL


